query ConversionRequestById($id: UUID!) {
  conversionRequestById(id: $id) {
    id
    creatorId
    authorityId
    dataObjectId
    sourceNationCode
    targetNationCodes
    createdAt
    updatedAt
    completedAt
    authority {
      id
      name
      email
      nation {
        id
        nationName
        nationCode
      }
    }
    dataObject {
      id
      title
      description
      createdAt
      updatedAt
      metadata {
        id
        domain
        tags
      }
    }
  }
}
